Portfolio :Humburger menu
arnoldnekemiah/portfolio-new pull request #9
Opened 2023-05-16 10:55 UTC by arnoldnekemiah

-Configured Linters
-Added functionality on Hamburger menu
-

- [ ] 1.     When the user clicks (or taps) the hamburger button, the mobile menu appears.
- [ ] 2.     When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- [ ] 3.     When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- [ ] 4.     When the user clicks (or taps) any of the mobile menu options, the correct part of the page is displayed.

Below is a link to my closing partner's contribution
https://github.com/arnoldnekemiah/portfolio-new/commit/a6aacd0c6e2f71990cafb7b3e50777cf6df53aba

2023-05-16 12:35 UTC, osamaashraf6 requested changes
Hi @arnoldnekemiah 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![SoCloseAlmostGIF (3)](https://github.com/arnoldnekemiah/portfolio-new/assets/83360636/13c4a3a6-40b9-4a7f-b355-f6d369c22728)


## Highlights🎉🎉
- [x] Not linter errors present🚀
- [x] Good descriptive pull request😊
- [x]  Good following Githubflow💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 12:35 UTC, osamaashraf6 commented on index.html
> +              </ul>
- [ ] While you make a great effort 😃 I see that you let the user when clicking (or taps) any of the mobile menu options, the correct part of the page is displayed, but you don't make all the links display the correct part of the page just I see that the link for the contact when 🚀I click on it it is navigating me to the contact section, so it will be better if you make the other links when the user clicks on any one of them the correct section displayed 😊💯

- Click [here](https://www.loom.com/share/b69d1d934ffe40538be1833c101af92f) to see the loom video when I check your portfolio⤵️😊
> Click [Here](https://www.loom.com/share/44b46833c90f4854b8096c6b331e4c93) 😊⤵️to see my portfolio in the mobile menu to understand and see the difference between all the changes I requested from you 💯

2023-05-16 12:35 UTC, osamaashraf6 commented on index.html
> +                <li class="nav-link"><a href="#About-myself">About</a></li>
- [ ] It will be better 😃 if you make the width of the mobile menu to be full width like the Figma Design as you see in your case it is not full width and it is not nice 😊like the Figma Design, so let's make it nice like the Figma Design and attract the users💯😊

- Click [here](https://www.loom.com/share/b69d1d934ffe40538be1833c101af92f) to see the loom video when I check your portfolio⤵️😊
- Click [Here](https://www.loom.com/share/44b46833c90f4854b8096c6b331e4c93) 😊⤵️to see my portfolio in the mobile menu to understand and see the difference between all the changes I requested from you 💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
| ![image](https://github.com/arnoldnekemiah/portfolio-new/assets/83360636/20b3b5cf-3a3b-4e9b-bc86-b1efd7826a80)   |    ![image](https://github.com/arnoldnekemiah/portfolio-new/assets/83360636/5e1c6201-4e79-45f1-8d37-ff5cb3a95751)  |

2023-05-16 12:35 UTC, osamaashraf6 commented on index.html
> +            <div class="menu-popup" id="menu-popup">
- [ ] While you make a great effort 😃💯I see that there is a horizontal scroll in the page that makes the mobile menu not nice like the Figma Design, so it will be better if you fix the scroll of the page to make the design nice like the Figma 😊
- Click [here](https://www.loom.com/share/b69d1d934ffe40538be1833c101af92f) to see the loom video when I check your portfolio⤵️😊
> Click [Here](https://www.loom.com/share/44b46833c90f4854b8096c6b331e4c93) 😊⤵️to see my portfolio in the mobile menu to understand and see the difference between all the changes I requested from you 💯

2023-05-16 12:35 UTC, osamaashraf6 commented on index.html
> -              </ul>
- [ ] Kindly 😃 try to fix the mobile menu issue when I click on it in the mobile version and switch to the desktop version I see that the mobile menu is still existing, but we want On desktop size the hamburger menu button not visible as this from the requirements, so please 😊💯 try to fix that to make the mobile menu nice for the users😊🚀
- Click [Here](https://www.loom.com/share/b69d1d934ffe40538be1833c101af92f) to see the loom video when I check your portfolio⤵️😊
> Click [Here](https://www.loom.com/share/44b46833c90f4854b8096c6b331e4c93) 😊⤵️to see my portfolio in the mobile menu to understand and see the difference between all the changes I requested from you 💯

2023-05-16 16:29 UTC, IngDavidTM requested changes
## Hi @arnoldnekemiah  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

- [OPTIONAL] You've done a commendable job incorporating the necessary changes :+1:. However, there is an issue that occurs when the user attempts to load your page. Currently, the main screen immediately displays the mobile menu without requiring the user to click the hamburger button. It is important that you address this problem to ensure that the mobile menu functions as intended. Please make the necessary adjustments to resolve this issue.


https://github.com/arnoldnekemiah/portfolio-new/assets/105117832/3ec7139d-e063-4fbf-a159-0823caa7e68c



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 16:29 UTC, IngDavidTM commented on index.html
> +              </ul>
- [ ] You've done a fantastic job, as acknowledged by the previous reviewer. However, it is imperative that the options on your mobile menu direct the user to the correct section of the page. This implies that the portfolio option should lead to the works section, the about option to the about me section, and the contact option to the form :+1:.

2023-05-16 16:29 UTC, IngDavidTM commented on index.html
> +            <div class="menu-popup" id="menu-popup">
- [ ] The previous reviewer mentioned an issue with horizontal scrolling on your page, which negatively impacts the user experience and deviates from the intended design outlined in the Figma template. It is crucial that you address this issue promptly in order to ensure a seamless and consistent user experience, aligning with the original design specifications. Please make the necessary adjustments to rectify the horizontal scrolling problem :+1:.

2023-05-17 06:54 UTC, FrederickMih approved these changes
## Hi :raising_hand:  @arnoldnekemiah, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 


## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 06:57 UTC, merged